Convert icons to fill and remove inline styles
kiesraad/abacus pull request #379
Opened 2024-09-24 22:41 UTC by lkleuver

closes #376

2024-09-25 06:46 UTC, jorisleker requested changes
- [ ] on `/overview` the icon next to 'invoerders bezig' has lost it's color (should be green)
- [ ] in the progresslist, the current item --> icon is blue, should be black
- [ ] in the progresslist, when the current page has an error, the icon is red, should be black
- [ ] in the progresslist, when the current page has a warning, the icon is yellow, should be black

2024-09-25 07:47 UTC, jschuurk-kr commented on frontend/lib/icon/generated.tsx
Tests are failing because the `img` `role` has been removed.

2024-09-25 08:02 UTC, jorisleker commented
- [ ] in the progresslist, the pencil icon on the furthest page is now black, should be blue

2024-09-25 08:24 UTC, jorisleker approved these changes

2024-09-25 08:31 UTC, lkleuver commented on frontend/lib/icon/generated.tsx
you were a second too quick :)

2024-09-25 08:31 UTC, lkleuver commented on frontend/lib/icon/generated.tsx
I've removed role="img" from the Icon component since I've added it to all svg's, having nested role="img" broke the tests.

2024-09-25 12:30 UTC, jorisleker commented on frontend/lib/icon/svg/checkVerified.svg
@lkleuver haven't seen this in the UI yet, but looks like this icon is broken

2024-09-26 07:16 UTC, praseodym requested changes
Like @jorisleker said, some of the icons look broken in the GitHub PR preview.

2024-09-27 07:58 UTC, lkleuver commented on frontend/lib/icon/svg/checkHeart.svg
Some icons have something strange making outline stroke fail.
I've fixed up the heart, but error still has some small discrepancies

2024-09-27 08:00 UTC, lkleuver commented on frontend/lib/icon/svg/checkVerified.svg
this icon still had a stroke.
My illustrator skills are a bit rusty but should be fixed.

2024-09-27 09:45 UTC, Lionqueen94 approved these changes

2024-09-27 11:05 UTC, jorisleker approved these changes

2024-09-27 11:28 UTC, merged