Implement custom radiobuttons + choicelist component
kiesraad/abacus pull request #435
Opened 2024-10-08 19:55 UTC by Lionqueen94

2024-10-09 07:02 UTC, jorisleker requested changes
- ✅ styling of radio's looks okay (all states)
- ✅ styling and behavior of checkbox is still ok. (can't retest a group of checkboxes though, because we don't have that yet)
- ❌ when hovering, the label has a hand/pointer cursor, the radio has a default cursor. Could we use pointer for both?
- ❌ padding/margin left of radio's should be removed; radio's should left align with elements above and below it
- ❌ when using tab to navigate through the page, it is now impossible to continu to the submit button from the choice group. Please compare to vanilla html form, behavior should be same. 
- ❌ having to click a radio twice is not expected behavior. Don't know exactly when/how this happens, but it should not. Clicking a radiobutton or it's label should immediately change it's state to checked.

2024-10-09 12:33 UTC, Lionqueen94 commented
> Tested on MacOS (Chrome, Safari, Firefox):
> 
>     * ✅ styling of radio's looks okay (all states)
> 
>     * ✅ styling and behavior of checkbox is still ok. (can't retest a group of checkboxes though, because we don't have that yet)
> 
>     * ❌ when hovering, the label has a hand/pointer cursor, the radio has a default cursor. Could we use pointer for both?
> 
>     * ❌ padding/margin left of radio's should be removed; radio's should left align with elements above and below it
> 
>     * ❌ when using tab to navigate through the page, it is now impossible to continu to the submit button from the choice group. Please compare to vanilla html form, behavior should be same. (might be fixed in [Navigating form sections and focus state #305](https://github.com/kiesraad/abacus/issues/305)?)
> 
>     * ❌ having to click a radio twice is not expected behavior. Don't know exactly when/how this happens, but it should not. Clicking a radiobutton or it's label should immediately change it's state to checked.

Fixed the cursor, padding and margin in ee2a9bb68e47997ca8e6eba521efddb11ca656e6
The navigate issue should indeed be fixed by merging my other pr
We will investigate the sometimes needed double click and hopefully figure out how to fix it

2024-10-10 08:26 UTC, jorisleker approved these changes

2024-10-10 08:27 UTC, jorisleker commented
LGTM now @Lionqueen94! Let's make sure to check the tab/navigation issue after merging this to main

2024-10-10 08:59 UTC, oliver3 approved these changes

2024-10-10 09:11 UTC, merged