Fixed showing of badge on data entru page (pencil should not be shown)
kiesraad/abacus pull request #451
Opened 2024-10-14 09:41 UTC by Lionqueen94

Closes #422

2024-10-14 12:00 UTC, oliver3 approved these changes

2024-10-14 15:26 UTC, cikzh approved these changes

2024-10-15 06:49 UTC, jorisleker requested changes
Icon is shown when it should be, and not shown when it should not be 👌 
The size of the icon does not match the design anymore (it's too small)

2024-10-15 07:50 UTC, Lionqueen94 commented
> Icon is shown when it should be, and not shown when it should not be 👌 The size of the icon does not match the design anymore (it's too small)

In the design https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=5401-30463&node-type=instance&m=dev is says 1rem for the icon size. I've now changed it to 1.25rem. Any bigger and the badge gets bigger overall. Is it correct now or should the badge itself be a bit bigger?

2024-10-15 07:52 UTC, cikzh submitted a review, later dismissed

2024-10-15 08:39 UTC, jorisleker approved these changes

2024-10-15 08:57 UTC, cikzh approved these changes

2024-10-15 09:27 UTC, merged