Show election in the navbar
kiesraad/abacus pull request #478
Opened 2024-10-21 08:11 UTC by oliver3

Fixes https://github.com/kiesraad/abacus/pull/453#discussion_r1804747108
- Added clickable election name on `/elections/1/polling-stations`
- Added election name on `/elections/1`
- Remove padding on first link in the navbar to align left with the rest of the page
<img width="452" alt="image" src="https://github.com/user-attachments/assets/13b74113-1871-4121-8be0-f08b866491b1">

2024-10-22 07:35 UTC, jschuurk-kr approved these changes

2024-10-22 07:40 UTC, jorisleker requested changes
We already have `elections.location` in our database, which is one of the attributes that should be shown in this navbar element as well. Could you add this? 

![image](https://github.com/user-attachments/assets/838b4bf9-53a7-4c02-848a-8942aaf99d78)

The element is constructed as follows:
- regional scope / role of polling station in this election (GSB/HSB/CSB); not in database yet, implemented later
- code / number of the region (gemeentenummer, kieskring); not in database yet; implemented later
- name of the region (gemeente, kieskring, provincie, waterschap); `elections.location`
- name of the election: `elections.name`. 

All items together are 1 link to `/elections/:election_id`

2024-10-23 07:41 UTC, Lionqueen94 approved these changes

2024-10-23 07:41 UTC, oliver3 commented
Thanks for the thorough clarification @jorisleker ! I've added the location

2024-10-23 14:39 UTC, jorisleker submitted a review, later dismissed
LGTM!

2024-10-24 07:51 UTC, jschuurk-kr commented on frontend/app/module/data_entry/polling_station/PollingStationLayout.test.tsx
> +    expect(within(nav).getByRole("link", { name: new RegExp(election.name) })).toHaveAttribute(
```suggestion
    expect(within(nav).getByRole("link", { name: /election.name/ })).toHaveAttribute(
```

RTL [documentation has](https://testing-library.com/docs/queries/about#textmatch) this way of doing regex. We also do it that way in some other tests.

2024-10-24 07:54 UTC, jschuurk-kr commented on frontend/app/module/data_entry/polling_station/PollingStationLayout.test.tsx
> +    expect(within(nav).getByRole("link", { name: new RegExp(election.name) })).toHaveAttribute(
never mind, bad idea with variables

2024-10-24 08:04 UTC, jschuurk-kr approved these changes

2024-10-24 11:28 UTC, merged