Move text to translations
kiesraad/abacus pull request #549
Opened 2024-11-05 10:22 UTC by marlonbaeten

Work on #520

2024-11-05 13:32 UTC, lkleuver approved these changes

2024-11-05 14:10 UTC, praseodym requested changes
See conversation. There's also a merge conflict now.

2024-11-05 20:42 UTC, Lionqueen94 approved these changes

2024-11-06 08:59 UTC, praseodym approved these changes

2024-11-06 10:27 UTC, merged