Closes #669 and added more translations
kiesraad/abacus pull request #699
Opened 2024-12-06 12:19 UTC by Lionqueen94

2024-12-06 14:16 UTC, praseodym submitted a review, later dismissed

2024-12-09 14:36 UTC, jorisleker requested changes
Not sure whether you touched this, but looked into the login form because the file was changed), but spacing between the submit button bar and the form is missing.

Column added to the overview page (scope of the ticket) looks good.
<img width="403" alt="Scherm­afbeelding 2024-12-09 om 15 33 26" src="https://github.com/user-attachments/assets/4c52dfd1-f39d-42cb-ab30-056c9a0f0c25">

2024-12-09 21:51 UTC, Lionqueen94 commented
> Not sure whether you touched this, but looked into the login form because the file was changed), but spacing between the submit button bar and the form is missing.
> 
> Column added to the overview page (scope of the ticket) looks good. <img alt="Scherm­afbeelding 2024-12-09 om 15 33 26" width="403" src="https://private-user-images.githubusercontent.com/3286523/393873983-4c52dfd1-f39d-42cb-ab30-056c9a0f0c25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NzgwMzQsIm5iZiI6MTczMzc3NzczNCwicGF0aCI6Ii8zMjg2NTIzLzM5Mzg3Mzk4My00YzUyZGZkMS1mMzlkLTQyY2ItYWIzMC0wNTZjOWEwZjBjMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMjA1NTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQ3OGM1ODhjYmZkZjZhOWZmMGE5NDllNTZlMzM1MTE0OWM4NjU1ZjUxM2E0MDMxOTJkMTIzZjRiZjI0YzNhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TPf8iPEn8ZE4-W4LIcpS6QjsRjZx_SQm2TX6UvEmDPg">

Not sure when it was broken, but it's fixed now in 32750aa7624cdd37c3f3e05f87281848aca3c479

2024-12-10 09:42 UTC, jorisleker submitted a review, later dismissed

2024-12-10 10:18 UTC, oliver3 approved these changes
Many improvements!

2024-12-10 10:28 UTC, Lionqueen94 commented on frontend/app/module/election/page/OverviewPage.tsx
> +              <Table.Column>{t(`election.${!isAdministrator ? "location" : "level_polling_station"}`)}</Table.Column>
```suggestion
              <Table.Column>{!isAdministrator ? t("election.location") : t("election.level_polling_station")}</Table.Column>
```

2024-12-10 10:29 UTC, Lionqueen94 commented on frontend/app/module/election/page/OverviewPage.tsx
> +          <h1>{t(`election.${isAdministrator ? "manage" : "title.plural"}`)}</h1>
Fair point, I changed both in fe95eecee102cdcbed7582e23a6f3ffa9e669fd4

2024-12-10 11:30 UTC, praseodym approved these changes
lgtm! Next time please make separate pull requests for unrelated changes.

2024-12-10 15:31 UTC, merged