Validate first and second data entries are equal
kiesraad/abacus pull request #745
Opened 2024-12-12 14:04 UTC by praseodym

Only create a polling station result when the first and second data
entries are equal, otherwise return the new `FirstSecondEntryDifferent`
status.

This new status is also added to the election status page (for coordinators).

This PR depends on changes from #740 (included as the first two commits), so draft until that PR is merged.

2024-12-16 08:23 UTC, jschuurk-kr commented on frontend/lib/ui/Badge/Badge.stories.tsx
> +        <Badge key={type} type={type} showIcon />
If we wrap this in a `<div id={type}>`, then we can get rid of the `.nth()`s in the e2e test. And we can expand the e2e test to check for `.toHaveAttribute('data-icon', 'IconPencil');` where relevant.

2024-12-16 09:54 UTC, oliver3 commented
You can still try and start data entry for a polling station that has differences, and will get an error message if you do so.

<img width="520" alt="image" src="https://github.com/user-attachments/assets/277a0225-b6d9-4391-a25a-b0d1f1fe4c05" />

2024-12-16 10:00 UTC, oliver3 reviewed
I was not expecting the `finalise` call to return an HTTP Ok response if there were errors actually, but I don't have a better suggestion because returning an error while the finalised_at fields are changed is also not an option..

2024-12-16 10:20 UTC, praseodym commented
> I was not expecting the `finalise` call to return an HTTP Ok response if there were differences actually, but I don't have a better suggestion because returning an error while the finalised_at fields are changed is also not an option..

For the typist (invoerder) everything is ok, the coordinator that needs to take action to resolve those differences (#130).

2024-12-17 12:57 UTC, Lionqueen94 commented
> You can still try and start data entry for a polling station that has differences, and will get an error message if you do so.

Fixed in 67247cfb4d8cef88970c77d30dc8b5b07a99c467

2024-12-17 12:57 UTC, Lionqueen94 commented on frontend/app/module/election/page/ElectionStatusPage.tsx
>      case "unfinished":
Improved in 67247cfb4d8cef88970c77d30dc8b5b07a99c467

2024-12-17 14:18 UTC, oliver3 approved these changes

2024-12-18 09:32 UTC, jorisleker requested changes
See last comment

2024-12-19 12:57 UTC, Lionqueen94 commented
> > > You can still try and start data entry for a polling station that has differences, and will get an error message if you do so.
> > 
> > 
> > Fixed in [67247cf](https://github.com/kiesraad/abacus/commit/67247cfb4d8cef88970c77d30dc8b5b07a99c467)
> 
> I can still trigger this error:
> 
>     * create two entries for a polling station that are different
> 
>     * on the pollingstationchoice page, enter the number of that polling station
> 
>     * click 'beginnen'
> 
>     * you will go to data entry and get this modal:
>       ![Scherm­afbeelding 2024-12-18 om 10 17 12](https://private-user-images.githubusercontent.com/3286523/396840165-2aadfe0b-9ab3-46a2-a89a-0dcab52bc03b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTMzNTAsIm5iZiI6MTczNDYxMzA1MCwicGF0aCI6Ii8zMjg2NTIzLzM5Njg0MDE2NS0yYWFkZmUwYi05YWIzLTQ2YTItYTg5YS0wZGNhYjUyYmMwM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTlUMTI1NzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjExMzM0MmVmYjY2YTM5NzE4NjBkZGRmMTIwMzRiNjg1NmU4NmFjODhkZTQyN2E5MWM3ZDAxN2M5NDdiMTI0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.akvO4uy1GMAMvT0bKx3bcch_9I2QdgOPNSUSSQ4PEPo)
> 
>     * there is no way to close the modal, both buttons and the close icon will trigger it again
> 
> 
> Suggested fix: if the user presses 'beginnen', show the error we also show when the user tries to go to polling station that has finalized input: ![Scherm­afbeelding 2024-12-18 om 10 19 39](https://private-user-images.githubusercontent.com/3286523/396841068-21ed4033-a060-476d-a162-4387b6982b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTMzNTAsIm5iZiI6MTczNDYxMzA1MCwicGF0aCI6Ii8zMjg2NTIzLzM5Njg0MTA2OC0yMWVkNDAzMy1hMDYwLTQ3NmQtYTE2Mi00Mzg3YjY5ODJiMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTlUMTI1NzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTkyMjQzZGVlZjNhYmVjNTVkMjAyMWRiZTNmZTdkNDY3ZDFhZjYwZWQ0MjM1YzVmMzY3ZjZlYWE0MzE5OTQ1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.--8E7uLeVRVGvnEQnF_5yGSBoFIS0ELFScWmiWgrdQM)
> 
> Bonus points: fix the layout bug in the "Stembureau 2 (Buurtcentrum de Mattenklopper) is al twee keer ingevoerd" feedback. This should be 1 sentence, instead of 3 inline blocks

Fixed in 105fac2aef1e4321d71003b8b3202314477f0d69. Please re-test :smile:

2024-12-19 13:29 UTC, praseodym reviewed
lgtm, but can't approve because I'm the PR author 🙃

2024-12-19 14:37 UTC, jorisleker approved these changes

2024-12-20 09:57 UTC, cikzh approved these changes
Reviewed by both me and @rnijveld

2024-12-20 10:40 UTC, merged